# Generated by Django 6.0.6 on 2026-06-20 02:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nome_profissional', models.CharField(max_length=100)),
                ('tipo_servico', models.CharField(choices=[('consulta', 'Consulta'), ('retorno', 'Retorno'), ('vacina', 'Vacina'), ('banho', 'Banho'), ('tosa', 'Tosa'), ('banho_e_tosa', 'Banho e Tosa')], max_length=20)),
                ('queixa', models.CharField(blank=True, max_length=255)),
                ('data_hora_inicio', models.DateTimeField()),
                ('duracao_minutos', models.PositiveIntegerField(default=30)),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('confirmado', 'Confirmado'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado'), ('faltou', 'Faltou')], default='agendado', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to='pets.pet')),
            ],
            options={
                'ordering': ['data_hora_inicio'],
            },
        ),
    ]
