# Generated by Django 6.0.6 on 2026-07-08 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='tipo_servico',
            field=models.CharField(choices=[('consulta', 'Consulta'), ('retorno', 'Retorno'), ('vacina', 'Vacina'), ('banho', 'Banho'), ('tosa', 'Tosa'), ('banho_e_tosa', 'Banho e Tosa'), ('banho_e_tosa_higienica', 'Banho e Tosa Higiênica')], max_length=50),
        ),
    ]
