# Generated by Django 6.0.6 on 2026-06-23 02:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(max_length=150)),
                ('cargo', models.CharField(choices=[('Veterinário', 'Veterinário'), ('tosador', 'Tosador'), ('banhista', 'Banhista'), ('Outro', 'Outro')], max_length=20)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('profissional', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='veterinario', serialize=False, to='veterinarios.profissional')),
                ('crmv', models.CharField(max_length=20, unique=True)),
                ('especialidade', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
