# Generated by Django 6.0.6 on 2026-06-23 02:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atendimentos', '0001_initial'),
        ('pets', '0001_initial'),
        ('veterinarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('data_consulta', models.DateTimeField()),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('diagnostico', models.TextField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('prescricao', models.TextField(blank=True)),
                ('retorno_recomendado', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atendimento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prontuario', to='atendimentos.atendimento')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prontuarios', to='pets.pet')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prontuarios', to='veterinarios.veterinario')),
            ],
            options={
                'ordering': ['-data_consulta'],
            },
        ),
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_vacina', models.CharField(max_length=100)),
                ('data_aplicacao', models.DateField()),
                ('data_retorno', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacinas', to='pets.pet')),
                ('prontuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacinas', to='prontuario.prontuario')),
            ],
            options={
                'ordering': ['-data_aplicacao'],
            },
        ),
    ]
