# Generated by Django 6.0.6 on 2026-06-20 02:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tutores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=50)),
                ('raca', models.CharField(blank=True, max_length=50)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=1)),
                ('castrado', models.BooleanField(default=False)),
                ('vermifugado', models.BooleanField(default=False)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pets', to='tutores.tutor')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
