# Generated by Django 6.0.6 on 2026-07-05 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='ccor',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
