# Generated by Django 6.0.6 on 2026-07-05 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_pet_ccor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='ccor',
            new_name='cor',
        ),
    ]
