# Generated by Django 6.0.6 on 2026-07-08 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_rename_ccor_pet_cor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='peso',
        ),
    ]
